### ISSUE TITLE
How can I supply max and per parameters to throttle from activerecord query

### ISSUE THREAD

**Issue by sachinsaxena1996** [gottfrois/grape-attack#10] opened 2016-05-10 13:24 UTC
I am using following code but it does not takes the values of max and per when i change it, untill I restart the rails server. due to which even if change the values of max_no_of_requests and time_period_in_secs for a particular api in database throttle still uses old max and per untill i restart server.

throttle max: ApiConfig.where(api_code_name: 'get_users').select(:max_no_of_requests).first.max_no_of_requests, per: ApiConfig.where(api_code_name: 'get_users').select(:time_period_in_secs).first.time_period_in_secs.seconds

Please look into this and suggest how can pick the max and per values using a activerecord query

**Comment by gottfrois** [comment] 2016-05-10 14:23
Yes it's because the `max` and `per` are define when the app starts and not at runtime. They would need to be ruby proc or lambdas like the `identifier`.

Duplicate of https://github.com/gottfrois/grape-attack/issues/4

**Comment by sachinsaxena1996** [comment] 2016-05-10 15:20
Hi,
I have tried using proc for max,per values as follows but it not worked:

**Comment by sachinsaxena1996** [comment] 2016-05-10 15:26
i have tried following but it not worked

throttle max: Proc.new{ApiConfig.where(api_code_name: 'get_users').select(:max_no_of_requests).first.max_no_of_requests}, per: Proc.new{ApiConfig.where(api_code_name: 'get_users').select(:time_period_in_secs).first.time_period_in_secs.seconds}

Please suggest why passing values for max and per as a proc above still not works

**Comment by gottfrois** [comment] 2016-05-10 15:39
Because it's simply not implemented :) I'll try to find some spare time to change that otherwise a pull request is welcome :)

**Comment by gottfrois** [comment] 2016-05-14 15:38
This is now implemented in `v0.3.0`

**Closed as completed by gottfrois** 2016-05-14 15:38 UTC
Labels: enhancement
